proxy:
    image: jwilder/nginx-proxy:latest
    ports:
        - "80:80"
    volumes:
        - /var/run/docker.sock:/tmp/docker.sock:ro

web:
    build: .
    ports:
        - "80"
    links:
        - mysql
    environment:
        - VIRTUAL_HOST=192.168.99.100

mysql:
    image: mysql:5.7
    volumes:
        - /var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: dev
        MYSQL_USER: dev
        MYSQL_PASSWORD: test123

